-- MySQL Script generated by MySQL Workbench
-- seg 03 nov 2025 19:18:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mothsinmywallet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mothsinmywallet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mothsinmywallet` ;
USE `mothsinmywallet` ;

-- -----------------------------------------------------
-- Table `mothsinmywallet`.`account_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mothsinmywallet`.`account_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mothsinmywallet`.`tag_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mothsinmywallet`.`tag_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tag_name` VARCHAR(45) NOT NULL,
  `tag_description` LONGTEXT NULL,
  `fk_account_table` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tag_table_account_table1_idx` (`fk_account_table` ASC) VISIBLE,
  CONSTRAINT `fk_tag_table_account_table1`
    FOREIGN KEY (`fk_account_table`)
    REFERENCES `mothsinmywallet`.`account_table` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mothsinmywallet`.`company_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mothsinmywallet`.`company_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NOT NULL,
  `company_description` LONGTEXT NULL,
  `fk_account_table` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_company_table_account_table1_idx` (`fk_account_table` ASC) VISIBLE,
  CONSTRAINT `fk_company_table_account_table1`
    FOREIGN KEY (`fk_account_table`)
    REFERENCES `mothsinmywallet`.`account_table` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mothsinmywallet`.`payment_method_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mothsinmywallet`.`payment_method_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_method` VARCHAR(45) NOT NULL,
  `payment_description` LONGTEXT NULL,
  `fk_account_table` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_table_account_table1_idx` (`fk_account_table` ASC) VISIBLE,
  CONSTRAINT `fk_payment_table_account_table1`
    FOREIGN KEY (`fk_account_table`)
    REFERENCES `mothsinmywallet`.`account_table` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mothsinmywallet`.`transaction_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mothsinmywallet`.`transaction_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title_transaction` VARCHAR(60) NOT NULL,
  `description_transaction` LONGTEXT NULL,
  `amount_transaction` DECIMAL(11,2) NOT NULL,
  `date_transaction` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_tag_table` INT NULL,
  `fk_company_table` INT NULL,
  `fk_payment_table` INT NULL,
  `fk_account_table` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transaction_table_tag_table_idx` (`fk_tag_table` ASC) VISIBLE,
  INDEX `fk_transaction_table_company_table1_idx` (`fk_company_table` ASC) VISIBLE,
  INDEX `fk_transaction_table_payment_table1_idx` (`fk_payment_table` ASC) VISIBLE,
  INDEX `fk_transaction_table_account_table1_idx` (`fk_account_table` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_table_tag_table`
    FOREIGN KEY (`fk_tag_table`)
    REFERENCES `mothsinmywallet`.`tag_table` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transaction_table_company_table1`
    FOREIGN KEY (`fk_company_table`)
    REFERENCES `mothsinmywallet`.`company_table` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transaction_table_payment_table1`
    FOREIGN KEY (`fk_payment_table`)
    REFERENCES `mothsinmywallet`.`payment_method_table` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transaction_table_account_table1`
    FOREIGN KEY (`fk_account_table`)
    REFERENCES `mothsinmywallet`.`account_table` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
